dist: trusty
sudo: required
language: node_js
node_js: 
    -   "14.13.1"
services:
    - docker

before_install:
    - sudo add-apt-repository --yes ppa:mc3man/trusty-media
    - sudo echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list.d/jessie-backports.list
    - sudo sed -i '/deb http:\/\/\(deb\|httpredir\).debian.org\/debian jessie.* main/d'  /etc/apt/sources.list
    - sudo apt-get -o Acquire::Check-Valid-Until=false update
    - sudo apt-get update
    - sudo apt-get install ffmpeg

script: npm test

